name: flameguard2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.21
  - pip=25.0
  - numpy=2.0.2
  - pandas=2.2.3
  - scipy=1.13.1
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - sqlalchemy=2.0.38
  - requests=2.32.3
  - pillow=11.1.0
  - tqdm=4.67.1
  - fastapi=0.115.8
  - uvicorn=0.34.0
  - starlette=0.45.3
  - pydantic=2.10.6
  - email-validator=2.2.0
  - python-dotenv=1.0.1
  - httpx=0.28.1
  - typer=0.15.1
  - rich=13.9.4
  - vc==14.42
  - vs2015_runtime==14.42.34433
  - pip:
      - opencv-python==4.11.0.86
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - dnspython==2.7.0
      - exceptiongroup==1.2.2
      - fastapi-cli==0.0.7
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - packaging==24.2
      - py-cpuinfo==9.0.0
      - pycparser==2.22
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.2
      - rich-toolkit==0.13.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - ultralytics==8.3.74
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - watchfiles==1.0.4
      - websockets==14.2
      - zipp==3.21.0
